backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from backend import views, drivers_views, routes_view, stations_view, vehicles_views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_page, name='logout'),
    # Routes
    path('routes/', routes_view.list_routes, name='list_routes'),
    path('routes/add/', routes_view.add_route, name='add_route'),
    path('routes/edit/<pk>/', routes_view.edit_route),
    path('routes/del/<pk>/', routes_view.del_route),
    path('routes/detail/<pk>/', routes_view.detail_route),

    # Stations
    path('stations/', stations_view.list_stations, name='list_stations'),
    path('stations/add/', stations_view.add_station, name='add_station'),
    path('stations/edit/<pk>/', stations_view.edit_station),
    path('stations/del/<pk>/', stations_view.del_station),

    # Vehicles
    path('vehicles/', vehicles_views.list_vehicles, name='list_vehicles'),
    path('vehicles/add/', vehicles_views.add_vehicle, name='add_vehicle'),
    path('vehicles/edit/<pk>/', vehicles_views.edit_vehicle),
    path('vehicles/del/<pk>/', vehicles_views.del_vehicle),

    # Drivers
    path('drivers/', drivers_views.list_drivers, name='list_drivers'),
    path('drivers/add/', drivers_views.add_driver, name='add_driver'),
    path('drivers/edit/<pk>/', drivers_views.edit_driver),
    path('drivers/del/<pk>/', drivers_views.del_driver),
    path('drivers/detail/<pk>/', drivers_views.detail_driver),

    # XML
    path('xml/', views.add_xml, name='add_xml')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
]

backend/models.py
from django.db import models


class Route(models.Model):
    BUS = 'BS'
    SHUTTLE = 'SE'
    TRAM = 'TM'
    TYPE_CHOICE = [
        (BUS, 'Автобус'),
        (SHUTTLE, 'Маршрутное такси'),
        (TRAM, 'Трамвай')
    ]

    code = models.CharField(max_length=50, unique=True)
    start = models.TimeField()
    end = models.TimeField()
    type_route = models.CharField(max_length=2, choices=TYPE_CHOICE, default=BUS)
    map_city = models.ImageField(default='maps/none.png', upload_to='maps', unique=True)

    def __str__(self):
        return self.code

class Station(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    route = models.ForeignKey(Route, on_delete=models.SET_DEFAULT, default=1)

    def __str__(self):
        return self.name


class Vehicle(models.Model):
    BUS = 'BS'
    SHUTTLE = 'SE'
    TRAM = 'TM'
    TYPE_CHOICE = [
        (BUS, 'Автобус'),
        (SHUTTLE, 'Маршрутное такси'),
        (TRAM, 'Трамвай')
    ]

    name = models.CharField(max_length=100)
    capacity = models.IntegerField()
    type_vehicle = models.CharField(max_length=2, choices=TYPE_CHOICE, default=BUS)
    route = models.ForeignKey(Route, on_delete=models.SET_DEFAULT, default=1)

    def __str__(self):
        return self.name

class Driver(models.Model):
    name = models.CharField(max_length=100)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    birth_date = models.DateField()
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    avatar = models.ImageField(default='avatars/none.png', upload_to='avatars', unique=True)


    def __str__(self):
        return self.name

backend/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.views.generic.edit import FormView
from django import forms
from django.contrib.auth import login, authenticate
from backend.models import *
from django.forms.widgets import ClearableFileInput

class EmptyClearableFileInput(ClearableFileInput):
    initial_text = ''
    input_text = ''
    clear_checkbox_label = ''


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=255,
                             required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}),
                             help_text='Это поле обязательно')
    username = forms.CharField(min_length=3,
                               max_length=20,
                               help_text='Длина логина должна быть не меньше 3-х и не больше 20',
                               widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label='Логин:')
    password1 = forms.CharField(min_length=6,
                               max_length=35,
                               help_text='Длина пароля должна быть не меньше 6 и не больше 35',
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='Пароль:')
    password2 = forms.CharField(min_length=6,
                               max_length=35,
                               help_text='Длина пароля должна быть не меньше 6 и не больше 35',
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='Повторите пароль:')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label='Логин:')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='Пароль:')
    class Meta:
        model = User
        fields = ['username', 'password']


class RouteForm(forms.ModelForm):
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='Код:')
    start = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control timepicker'}, format='%H:%M'),
                            label='Начало работы:')
    end = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control timepicker'}, format='%H:%M'),
                          label='Окончание работы:')
    type_route = forms.ChoiceField(widget=forms.Select(attrs={'class': 'mdb-select md-form'}),
                                   choices=Route.TYPE_CHOICE,
                                   label='Тип маршрута/транспорта:')
    map_city = forms.ImageField(label='Карта')

    class Meta:
        model = Route
        fields = '__all__'


class DriverForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='Имя:')
    vehicle = forms.ModelChoiceField(queryset=Vehicle.objects.all(),
                                     widget=forms.Select(attrs={'class': 'mdb-select md-form'}),
                                     required=True,
                                     empty_label='Выберите транспорт')
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control datepicker'}, format='%d.%m.%Y'),
                                 input_formats=['%d.%m.%Y'],
                                 label='Дата рождения:')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}),
                             label='Email:')
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Телефон:')
    
    avatar = forms.ImageField(label='Аватар')

    class Meta:
        model = Driver
        fields = '__all__'

class StationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='Имя:')
    position = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label='Позиция:')
    route = forms.ModelChoiceField(queryset=Route.objects.filter(id__gt=1).all(),
                                   widget=forms.Select(attrs={'class': 'mdb-select md-form'}),
                                   required=True,
                                   empty_label='Выберите маршрут')
    class Meta:
        model = Station
        fields = '__all__'


class VehicleForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='Имя:')
    capacity = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                  label='Вместимость:')
    type_vehicle = forms.ChoiceField(widget=forms.Select(attrs={'class': 'mdb-select md-form'}),
                                     choices=Route.TYPE_CHOICE,
                                     label='Тип транспорта:')
    route = forms.ModelChoiceField(queryset=Route.objects.filter(id__gt=1).all(),
                                   widget=forms.Select(attrs={'class': 'mdb-select md-form'}),
                                   required=True,
                                   empty_label='Выберите маршрут')

    class Meta:
        model = Vehicle
        fields = '__all__'

class XMLForm(forms.Form):
    route = forms.ModelChoiceField(queryset=Route.objects.filter(id__gt=1).all(),
                                   widget=forms.Select(attrs={'class': 'mdb-select md-form'}),
                                   required=True,
                                   empty_label='Выберите маршрут')
    xml = forms.FileField(label='XML', widget=forms.FileInput(attrs={'accept': 'text/xml'}))

backend/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from backend.forms import *
from django.contrib import messages
from xml.dom import minidom as md

def index(request):
    return render(request, 'index.html')


def signin(request):
    if request.method == 'GET' and request.user.is_anonymous:
        return render(request, 'signin.html', context={'form': SignInForm()})
    elif request.user.is_anonymous:
        username = request.POST['username']
        password = request.POST['password']
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user_active = authenticate(username=username, password=password)
            if not(user_active is None):
                messages.info(request, 'Вы успешно авторизовались!')
                login(request, user_active)
                return redirect('index')
            else:
                messages.error(request, 'Не верный логин или пароль!')
                return render(request, 'signin.html', context={'form': SignInForm(data=request.POST)})
        messages.error(request, 'Ошибка при заполнении формы авторизации!')
        return render(request, 'signin.html', context={'form': SignInForm()})
    messages.warning(request, 'У вас нет доступа к этой странице!')
    return redirect('index')


# ASd2345gl23asfLsd12
def signup(request):
    if request.method == 'GET' and request.user.is_anonymous:
        return render(request, 'signup.html', context={'form': SignUpForm()})
    elif request.user.is_anonymous:
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Вы успешно зарегистрировались!')
        else:
            messages.error(request, 'Ошибка при заполнении формы')
            return render(request, 'signup.html', context={'form': SignUpForm()})
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        user = authenticate(username=username, password=password)
        if user is None:
            return redirect('signup')
        login(request, user)
        messages.info(request, 'Вы автоматически вошли после регистарции!')
    messages.warning(request, 'У вас нет доступа к этой странице.')
    return redirect('index')


def logout_page(request):
    if request.user.is_authenticated:
        logout(request)
        messages.info(request, 'Вы успешно вышли!')
        return redirect('index')
    else:
        messages.error(request, 'Пользователь не авторизован')
    return redirect('index')

def add_xml(request):
    if request.method == 'GET' and request.user.is_staff:
        return render(request, 'add_xml.html', context={'form': XMLForm()})
    elif request.user.is_staff:
        form = XMLForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            incst = form.cleaned_data['xml']
            resultXml = incst.read()
            doc = md.parseString(resultXml)

            stations = doc.getElementsByTagName('data')[0].getElementsByTagName('stations')
            vehicles = doc.getElementsByTagName('data')[0].getElementsByTagName('vehicles')
            route = Route.objects.get(pk=request.POST['route'])
            listNamesStations = []
            for station in stations:
                names = station.getElementsByTagName('name')
                positions = station.getElementsByTagName('position')[0].firstChild.data
                for name, position in zip(station.getElementsByTagName('name'), station.getElementsByTagName('position')):
                    r_name, r_position = name.firstChild.data, position.firstChild.data
                    new_station = Station(name=r_name, position=r_position, route=route)
                    new_station.save()
                    listNamesStations.append(r_name)

            listNamesVehicles = []
            for vehicle in vehicles:
                names = vehicle.getElementsByTagName('name')
                capacities = vehicle.getElementsByTagName('capacity')
                type_vs = vehicle.getElementsByTagName('type')
                for name, capacity, type_v in zip(names, capacities, type_vs):
                    r_name, r_capacity, r_type = name.firstChild.data, capacity.firstChild.data, type_v.firstChild.data
                    new_vehicle = Vehicle(name=r_name, capacity=r_capacity, type_vehicle=r_type, route=route)
                    new_vehicle.save()
                    listNamesVehicles.append(r_name)

            str_stations = ', '.join(listNamesStations)
            str_vehicles = ', '.join(listNamesVehicles)
            messages.info(request, f'XML файл успешно загружен для маршрута {route}')
            messages.info(request, f'Станции: {str_stations}')
            messages.info(request, f'Транспортные средства: {str_vehicles}')
            return redirect('add_xml')
        messages.warning(request, 'У вас нет доступа к этой странице.')
        return redirect('add_xml')

backend/templates/routes/add_route.html
{% extends "layouts/main_layout.html" %}

{% block title %}
    Laba 5 - Добавить маршрут
{% endblock %}

{% block content %}
    <div class='container d-flex justify-content-center'>
            
            <form method="POST" class='w-50' enctype="multipart/form-data">
                {% csrf_token %}
                {% include "layouts/messages.html" %}
                <div class='p-4 display-4 text-center'>Добавить маршрут</div>
                
                <div class="md-form">
                    {{form.code}}
                    <label for="id_code">{{form.code.label}}</label>
                </div>

                <div class="md-form">
                    {{form.start}}
                    <label for="id_start">{{form.start.label}}</label>
                </div>

                
                <div class="md-form">
                    {{form.end}}
                    <label for="id_end">{{form.end.label}}</label>
                </div>

                <div class="md-form">
                    {{form.type_route}}
                </div>

                <div class="md-form">
                    <div class="file-field">
                        <div class="btn btn-primary btn-sm float-left">
                            <span>{{form.map_city.label}}</span>
                        {{form.map_city}}
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Выберите файл">
                        </div>
                    </div>
                </div>

                <button type="submit" class='btn btn btn-mdb-color w-100' >Сохранить</button>
            </form>
    </div>

{% endblock %}

backend/templates/routes/detail_route.html
{% extends "layouts/main_layout.html" %}

{% block title %}
    Laba 5 - Просмотр маршрута
{% endblock %}

{% block content %}
    <div class='container d-flex justify-content-center flex-column align-items-center'>
            
        <div class='p-4 display-4 text-center'>Просмотр маршрута</div>

        <img class='img-thumbnail' src='{{route.map_city.url}}' width='250px'>

        <h4 class='pt-3'>Код: <b>{{route.code}}</b></h4>
        <h4 class='pt-3'>Начало работы: <b>{{route.start|time:"H:i"}}</b></h4>
        <h4 class='pt-3'>Конец работы: <b>{{route.end|time:"H:i"}}</b></h4>
        <h4 class='pt-3'>Тип транспорта/маршрута: <b>{{route.get_type_route_display}}</b></h4>   
    </div>

{% endblock %}

backend/templates/routes/edit_route.html
{% extends "layouts/main_layout.html" %}

{% block title %}
    Laba 5 - Изменить маршрут
{% endblock %}

{% block content %}
<div class='container d-flex justify-content-center'>
            
    <form method="POST" class='w-50' enctype="multipart/form-data">
        {% csrf_token %}
        {% include "layouts/messages.html" %}
        <div class='p-4 display-4 text-center'>Изменить маршрут</div>
        
        <div class="md-form">
            {{form.code}}
            <label for="id_code">{{form.code.label}}</label>
        </div>

        <div class="md-form">
            {{form.start}}
            <label for="id_start">{{form.start.label}}</label>
        </div>

        
        <div class="md-form">
            {{form.end}}
            <label for="id_end">{{form.end.label}}</label>
        </div>

        <div class="md-form">
            {{form.type_route}}
        </div>

        <div class="md-form">
            Текущий: <a href='{{ form.instance.map_city.url }}'>{{ form.instance.map_city }}</a>
            <div class="file-field">
                <div class="btn btn-primary btn-sm float-left">
                    <span>Картра</span>
                </div>
                <input type='file' name='map_city' id='id_map_city' accept='image/*'>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" placeholder="Выберите новый файл">
                </div>
            </div>
        </div>

        <button type="submit" class='btn btn btn-mdb-color w-100' >Сохранить</button>
    </form>
</div>


{% endblock %}

backend/templates/routes/list_routes.html
{% extends "layouts/main_layout.html" %}

{% block title %}
    Laba 5 - Список маршрутов
{% endblock %}

{% block content %}

<div class='container d-flex justify-content-center flex-column'>
    {% include "layouts/messages.html" %}
    <div class='p-4 display-4 text-center'>
        Список маршрутов <a class="btn btn-rounded btn-blue-grey" href='{{ fullurl }}/routes/add/'>Добавить </a>
    </div>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Код</th>
            <th scope="col">Начало</th>
            <th scope="col">Конец</th>
            <th scope="col">Тип маршрута</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% for route in routes %}
        <tr>
            <th scope="row">
                <h4>
                {% if route.code == 'null' %}
                    -
                {% else %}
                {{route.code }}
                {% endif %}
                </h4>
            </th>
            <td><h4>{{ route.start|time:"H:i" }}</h4></td>
            <td><h4>{{ route.end|time:"H:i" }}</h4></td>
            <td><h4>{{ route.get_type_route_display }}</h4></td>
            <td>
                <a href='{{ fullurl }}/routes/edit/{{ route.id }}/' >
                    <button class='btn btn btn-dark-green btn-sm w-100'>Изменить</button>
                </a>
            </td>
            <td>
                <form method='POST' action="{{ fullurl }}/routes/del/{{ route.id }}/">
                    {% csrf_token %}
                    <button type="submit" class='btn btn btn-danger btn-sm w-100' >Удалить</button>
                </form>
            </td>
            <td>
                <a href='{{ fullurl }}/routes/detail/{{ route.id  }}/' >
                    <button class='btn btn btn-indigo btn-sm w-100'>Просмотреть</button>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}